apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-config
  namespace: weather-app
data:
  database_url: "postgresql://user:password@postgres-service.weather-app.svc.cluster.local/weatherdb"
  flask_env: "production"
